import InitState;
import flixel.FlxG;
import flixel.FlxGame;
import flixel.FlxState;
import flixel.system.FlxSplash;
import flixel.util.FlxTimer;
import menu.MainMenuState;
import openfl.display.Sprite;
import play.PlayState;
