import InitState;
import ctDialogueBox.ctdb.CtDialogueBox;
import flixel.FlxCamera;
import flixel.FlxG;
import flixel.FlxGame;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.addons.display.FlxBackdrop;
import flixel.graphics.frames.FlxAtlasFrames;
import flixel.group.FlxSpriteGroup;
import flixel.math.FlxMath;
import flixel.math.FlxPoint;
import flixel.sound.FlxSound;
import flixel.system.FlxSplash;
import flixel.text.FlxText;
import flixel.tweens.FlxEase;
import flixel.tweens.FlxTween;
import flixel.util.FlxColor;
import flixel.util.FlxTimer;
import haxe.io.Path;
import hscript.Expr;
import hscript.Interp;
import menu.MainMenuOption;
import menu.MainMenuState;
import openfl.Assets;
import openfl.display.Sprite;
import play.PlayState;
import script.*;

using StringTools;
#if windows
import Sys;
#end
